from pathlib import Path
import json,hashlib,datetime
r=Path("D:/HAMON/canvas-file-search-5f566b5ec8ef/evidence/peer-mac")
result=json.loads((r/"targeted-result.json").read_text())
receipt={"reviewer":"chatgpt:5f566b5ec8ef:mac_continuity","at":datetime.datetime.now(datetime.timezone.utc).isoformat(),"decision":"accepted within reviewed scope","sourcePins":result["source_after"],"blindContract":"Read only outcome contract, froze distinct expected cases, then inspected complete new helper and exact CLI insertions/actual list_files function. Owner tests not read.","controls":{"passed":9,"total":9,"resultSha256":hashlib.sha256((r/"targeted-result.json").read_bytes()).hexdigest()},"findings":["Literal casefold handles partial unavailable names honestly and does not concatenate or canonically normalize names.","Normalized row occurrences/order and arbitrarily precise integer metadata survive the detached JSON copy; later caller mutation does not alter report.","Preflight validates whole selection before any API read. CLI branch reaches run_file_search before common CanvasClient construction.","Actual unchanged CanvasAPI list_files projection drops raw nonobjects and unprojected fields; the report correctly disclaims whole provider inventory or file availability.","Complete helper has bounded row/source/output/depth admission and returns only after all selected reads succeed; later read failure returns no partial model report.","Source read of CLI wrapper confirms close in finally, HTTPX logger restoration and structured errors; no independent CLI transport/stdout execution claim."],"limitations":["Nine authored in-memory helper/API projection groups, no live HTTP/provider/profile, no repeated owner suite/build.","Root/owner actual CLI transport and process/output receiving remain separate gates.","Initial blind-case JS number precision mistake was corrected before any product exposure, original initial file and correction receipt retained.","Missing evidence/source-freeze.json read was a path-discovery miss only; direct exact source SHA checks are authoritative."],"changes":"No product source edits; all three exact source hashes unchanged during targeted run."}
p=r/"independent-review.json"
with p.open("x",encoding="utf-8",newline="") as f:json.dump(receipt,f,indent=2);f.write("\n")
files=[]
for f in sorted(r.iterdir()):
 if f.is_file():files.append({"path":f.name,"size":f.stat().st_size,"sha256":hashlib.sha256(f.read_bytes()).hexdigest()})
(r/"manifest.json").write_text(json.dumps({"files":files},indent=2)+"\n",encoding="utf-8",newline="")
print(json.dumps({"reviewSha256":hashlib.sha256(p.read_bytes()).hexdigest(),"resultSha256":receipt["controls"]["resultSha256"],"manifestSha256":hashlib.sha256((r/"manifest.json").read_bytes()).hexdigest(),"files":len(files),"barContractSha256":hashlib.sha256(Path("D:/HAMON/offhand-bar-export-contract-5f566b5ec8ef.md").read_bytes()).hexdigest()}))
